version: '3.8'

services:
  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      # Mount package.json separately to prevent overwrites
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    networks:
      - portfolio-network
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s

networks:
  portfolio-network:
    driver: bridge